apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CapsuleBay
  description: Shell tooling - early / scratch
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/archive/CapsuleBay
  links:
    - url: https://github.com/gustav0thethird/CapsuleBay
      title: GitHub
      icon: github
  tags:
    - shell
    - scratch
    - archive
spec:
  type: tool
  lifecycle: experimental
  owner: gtully
  system: archive
