apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CapsuleBay
  description: CapsuleBay is a hybrid CI/CD framework for modular, image-based capsule
    deployments with integrated security scanning.
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/archive/CapsuleBay
    yditj.home/capabilities: Self-contained deployment capsules; Automated build,
      push, scan, and deploy pipeline; Vault-based secret management; Per-service
      modular builds; Immutable image capsules; Automated VM lifecycle management
      via Proxmox API; Security scanning using Trivy and Snyk; Discord notifications
      for build status and details
  links:
  - url: https://github.com/gustav0thethird/CapsuleBay
    title: GitHub
    icon: github
  tags:
  - ci-cd
  - docker
  - security
  - deployment
  - automation
spec:
  type: tool
  lifecycle: experimental
  owner: gtully
  system: archive
