apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CapsuleBay
  description: CapsuleBay is a hybrid CI/CD framework for modular, image-based deployments
    with integrated security scanning.
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/archive/CapsuleBay
  links:
  - url: https://github.com/gustav0thethird/CapsuleBay
    title: GitHub
    icon: github
  tags:
  - ci-cd
  - docker
  - security
  - automation
  - deployment
spec:
  type: tool
  lifecycle: experimental
  owner: gtully
  system: archive
