version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: "portainer-${LAN_IP}"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      - LAN_IP=${LAN_IP}
    restart: unless-stopped

volumes:
  portainer_data:
